# src/docsynthfab/reports/run_manifest.py
# Recommended version ranges:
# - Python>=3.10,<3.14
#
# This module uses only the Python standard library.

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from .io_utils import _now_utc_iso, _write_json
from .label_schema import LABEL_SCHEMA_VERSION


RUN_MANIFEST_VERSION = "run-manifest-v1"


def _timestamp_version() -> str:
    """
    Return an automatic run/output version.

    This is intentionally generated by the backend so the user does not need
    to manually manage dataset/run versions.
    """
    return datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")


def write_run_manifest(
    path: Path,
    *,
    project_name: str,
    version: str,
    cfg_path: str,
    out_root: Path,
    pages_requested: int,
    pages_ok: int,
    pages_fail: int,
    seed: int,
    workers: int,
    splits: Dict[str, Any],
    export_targets: List[str],
    qc_summary: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Write the machine-readable run manifest.

    Version fields:
    - manifest_version: manifest JSON schema/contract version.
    - version: automatic run/output version based on UTC timestamp.
    - run_id: stable run identifier derived from the timestamp version.
    - generator_version: docsynthfab generator/config version passed by caller.
    """
    run_version = _timestamp_version()

    manifest = {
        "manifest_version": RUN_MANIFEST_VERSION,
        "version": run_version,
        "run_id": f"run-{run_version}",
        "project_name": project_name,
        "generator_version": str(version or "unknown"),
        "label_schema_version": LABEL_SCHEMA_VERSION,
        "created_at": _now_utc_iso(),
        "config_path": str(cfg_path),
        "out_root": str(out_root),
        "pages_requested": int(pages_requested),
        "pages_ok": int(pages_ok),
        "pages_fail": int(pages_fail),
        "seed": int(seed),
        "workers": int(workers),
        "splits": splits,
        "export_targets": list(export_targets or []),
        "outputs": {
            "images": "images/",
            "masks": "masks/",
            "annotations": "ann/",
            "ground_truth": "gt/",
            "splits": "splits/",
            "reports": "reports/",
            "exports": "exports/",
        },
        "qc_summary": qc_summary or {},
    }

    _write_json(path, manifest)
    return manifest



