# src/ai1_gen/orchestrator/param_schema.py
# Önerilen sürüm aralıkları:
# - Python>=3.10,<3.14

from __future__ import annotations

from typing import Dict, List

from .models import ParamField


_PARAM_FIELDS: List[ParamField] = [
    # =========================================================
    # BASIC
    # =========================================================
    ParamField(
        key="run.pages",
        label="Pages",
        group="Run",
        field_type="int",
        default=100,
        minimum=1,
        help_text="Üretilecek toplam sayfa sayısı.",
        visibility="basic",
    ),
    ParamField(
        key="run.workers",
        label="Workers",
        group="Run",
        field_type="int",
        default=4,
        minimum=1,
        help_text="Paralel worker sayısı.",
        visibility="basic",
    ),
    ParamField(
        key="run.seed",
        label="Seed",
        group="Run",
        field_type="int",
        default=1337,
        help_text="Deterministik tekrar üretim için tohum değeri.",
        visibility="basic",
    ),
    ParamField(
        key="io.out_root",
        label="Output Root",
        group="Run",
        field_type="path",
        default="",
        help_text="Çıktı klasörü.",
        visibility="basic",
    ),

    ParamField(
        key="run.export_targets",
        label="Export Targets",
        group="Output / Export",
        field_type="json",
        default=["native", "segformer", "coco"],
        help_text='Active export targets. Example: ["native", "segformer", "coco"]. Future targets: yolo, paddleocr_det, paddleocr_rec, trocr, latex_ocr, table_parser.',
        visibility="basic",
    ),

    ParamField(
        key="page.default_size",
        label="Default Page Size",
        group="Page",
        field_type="enum",
        default="a4_portrait",
        choices=[
            "a4_portrait",
            "a4_landscape",
            "letter_portrait",
            "letter_landscape",
            "legal_portrait",
            "legal_landscape",
            "a5_portrait",
            "a5_landscape",
            "b5_portrait",
            "b5_landscape",
            "executive_portrait",
            "executive_landscape",
            "tabloid_portrait",
            "tabloid_landscape",
        ],
        help_text="Varsayılan sayfa boyutu.",
        visibility="basic",
    ),
    ParamField(
        key="content.text_mode",
        label="Text Mode",
        group="Content",
        field_type="enum",
        default="mixed",
        choices=["chars", "words", "sentences", "mixed"],
        help_text="Metin üretim modu.",
        visibility="basic",
    ),
    ParamField(
        key="content.text_order",
        label="Text Order",
        group="Content",
        field_type="enum",
        default="random",
        choices=["random", "sequential"],
        help_text="Kelime/cümlelerin rastgele ya da sıralı seçimi.",
        visibility="basic",
    ),
    ParamField(
        key="content.has_equation_prob",
        label="Equation Probability",
        group="Content",
        field_type="float",
        default=0.40,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Sayfada denklem olma olasılığı.",
        visibility="basic",
    ),
    ParamField(
        key="content.has_table_prob",
        label="Table Probability",
        group="Content",
        field_type="float",
        default=0.20,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Sayfada tablo olma olasılığı.",
        visibility="basic",
    ),
    ParamField(
        key="content.has_figure_prob",
        label="Figure Probability",
        group="Content",
        field_type="float",
        default=0.05,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Sayfada figür olma olasılığı.",
        visibility="basic",
    ),
    ParamField(
        key="augment.enable",
        label="Enable Augment",
        group="Augment",
        field_type="bool",
        default=True,
        help_text="Render sonrası augment işlemlerini aç/kapat.",
        visibility="basic",
    ),

    # =========================================================
    # ADVANCED / YAML MANAGER
    # =========================================================
    ParamField(
        key="ui.yaml_manager.enable_raw_override",
        label="Enable Raw YAML Override",
        group="YAML Manager",
        field_type="bool",
        default=False,
        help_text="Raw YAML override panelini etkinleştirir.",
        visibility="advanced",
    ),
    ParamField(
        key="ui.yaml_manager.allow_export",
        label="Allow YAML Export",
        group="YAML Manager",
        field_type="bool",
        default=True,
        help_text="Mevcut effective config'i YAML olarak dışa aktarmaya izin verir.",
        visibility="advanced",
    ),
    ParamField(
        key="ui.yaml_manager.allow_reset_to_baseline",
        label="Allow Reset To Baseline",
        group="YAML Manager",
        field_type="bool",
        default=True,
        help_text="GUI'de baseline/default YAML'a dönme butonunu etkinleştirir.",
        visibility="advanced",
    ),
    ParamField(
        key="ui.yaml_manager.show_effective_preview",
        label="Show Effective YAML Preview",
        group="YAML Manager",
        field_type="bool",
        default=True,
        help_text="Effective config önizleme alanını gösterir.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / RUN
    # =========================================================
    ParamField(
        key="run.fail_fast",
        label="Fail Fast",
        group="Run",
        field_type="bool",
        default=False,
        help_text="İlk ciddi hata oranında koşuyu durdurur.",
        visibility="advanced",
    ),
    ParamField(
        key="run.max_fail_ratio",
        label="Max Fail Ratio",
        group="Run",
        field_type="float",
        default=0.02,
        minimum=0.0,
        maximum=1.0,
        step=0.001,
        help_text="İzin verilen maksimum hata oranı.",
        visibility="advanced",
    ),
    ParamField(
        key="run.jsonl_flush_batch_size",
        label="JSONL Flush Batch Size",
        group="Run",
        field_type="int",
        default=50,
        minimum=1,
        help_text="JSONL tamponunun kaç kayıtta bir flush edileceği.",
        visibility="advanced",
    ),
    ParamField(
        key="run.max_pending_mult",
        label="Max Pending Multiplier",
        group="Run",
        field_type="float",
        default=2.0,
        minimum=1.0,
        step=0.1,
        help_text="Worker başına pending iş çarpanı.",
        visibility="advanced",
    ),
    ParamField(
        key="run.max_pending_min",
        label="Max Pending Minimum",
        group="Run",
        field_type="int",
        default=8,
        minimum=1,
        help_text="Minimum pending iş sayısı.",
        visibility="advanced",
    ),
    ParamField(
        key="run.worker.max_tries",
        label="Worker Max Tries",
        group="Run",
        field_type="int",
        default=4,
        minimum=1,
        help_text="Bir sayfa için maksimum tekrar deneme sayısı.",
        visibility="advanced",
    ),
    ParamField(
        key="run.worker.disable_augment_on_try",
        label="Disable Augment On Try",
        group="Run",
        field_type="int",
        default=2,
        minimum=1,
        help_text="Belirli denemeden sonra augment kapatılır.",
        visibility="advanced",
    ),
    ParamField(
        key="run.worker.jitter_seed_step",
        label="Jitter Seed Step",
        group="Run",
        field_type="int",
        default=10000019,
        minimum=1,
        help_text="Retry seed varyasyonu için adım değeri.",
        visibility="advanced",
    ),
    ParamField(
        key="run.worker.fallback_dpi",
        label="Fallback DPI",
        group="Run",
        field_type="int",
        default=300,
        minimum=72,
        help_text="Fallback render DPI değeri.",
        visibility="advanced",
    ),
    ParamField(
        key="run.splits.train",
        label="Train Split",
        group="Run",
        field_type="float",
        default=0.80,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Train split oranı.",
        visibility="advanced",
    ),
    ParamField(
        key="run.splits.val",
        label="Val Split",
        group="Run",
        field_type="float",
        default=0.10,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Validation split oranı.",
        visibility="advanced",
    ),
    ParamField(
        key="run.splits.test",
        label="Test Split",
        group="Run",
        field_type="float",
        default=0.10,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Test split oranı.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / PAGE
    # =========================================================
    ParamField(
        key="page.size_name",
        label="Legacy Size Name",
        group="Page",
        field_type="str",
        default="A4",
        help_text="Geriye dönük uyumluluk için eski sayfa ismi.",
        visibility="advanced",
    ),
    ParamField(
        key="page.dpi_choices",
        label="DPI Choices",
        group="Page",
        field_type="json",
        default=[200, 300],
        help_text="DPI seçim listesi.",
        visibility="advanced",
    ),
    ParamField(
        key="page.bg_color_rgb",
        label="Background RGB",
        group="Page",
        field_type="color_rgb",
        default=[255, 255, 255],
        help_text="Arka plan rengi.",
        visibility="advanced",
    ),
    ParamField(
        key="page.size_dist",
        label="Page Size Distribution",
        group="Page",
        field_type="json",
        default={},
        help_text="Sayfa boyutu dağılımı.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / DISTRIBUTION
    # =========================================================
    ParamField(
        key="dist.density_dist",
        label="Density Distribution",
        group="Distribution",
        field_type="json",
        default={},
        help_text="Density level dağılımı.",
        visibility="advanced",
    ),
    ParamField(
        key="dist.scale_dist",
        label="Scale Distribution",
        group="Distribution",
        field_type="json",
        default={},
        help_text="Scale profile dağılımı.",
        visibility="advanced",
    ),
    ParamField(
        key="dist.noise_level_dist",
        label="Noise Level Distribution",
        group="Distribution",
        field_type="json",
        default={"clean": 0.3, "medium": 0.5, "heavy": 0.2},
        help_text="Noise level dağılımı.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / LAYOUT
    # =========================================================
    ParamField(
        key="layout.targets",
        label="Layout Targets",
        group="Layout",
        field_type="json",
        default={},
        help_text="Density seviyelerine göre layout hedefleri.",
        visibility="advanced",
    ),
    ParamField(
        key="density_thresholds",
        label="Density Thresholds",
        group="Layout",
        field_type="json",
        default={},
        help_text="Density threshold ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="thresholds",
        label="Legacy Thresholds",
        group="Layout",
        field_type="json",
        default={},
        help_text="Geriye dönük threshold alanı.",
        visibility="advanced",
    ),

    ParamField(
        key="layout.anchor.mode",
        label="Anchor Mode",
        group="Layout",
        field_type="enum",
        default="top_left",
        choices=["top_left", "top_center", "center", "custom"],
        help_text="Yerleşim başlangıç noktası modu.",
        visibility="advanced",
    ),
    ParamField(
        key="layout.anchor.x_px",
        label="Anchor X (px)",
        group="Layout",
        field_type="int",
        default=0,
        help_text="Custom anchor için X başlangıç koordinatı.",
        visibility="advanced",
    ),
    ParamField(
        key="layout.anchor.y_px",
        label="Anchor Y (px)",
        group="Layout",
        field_type="int",
        default=0,
        help_text="Custom anchor için Y başlangıç koordinatı.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / CONTENT
    # =========================================================
    ParamField(
        key="content.has_caption_prob",
        label="Caption Probability",
        group="Content",
        field_type="float",
        default=0.40,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Caption olma olasılığı.",
        visibility="advanced",
    ),
    ParamField(
        key="content.hard_negative_page_prob",
        label="Hard Negative Page Probability",
        group="Content",
        field_type="float",
        default=0.05,
        minimum=0.0,
        maximum=1.0,
        step=0.01,
        help_text="Hard negative sayfa olasılığı.",
        visibility="advanced",
    ),
    ParamField(
        key="content.source.words_csv",
        label="Words CSV",
        group="Content",
        field_type="path",
        default="data/content/words.csv",
        help_text="Kelime kaynağı CSV dosyası.",
        visibility="advanced",
    ),
    ParamField(
        key="content.source.sentences_csv",
        label="Sentences CSV",
        group="Content",
        field_type="path",
        default="data/content/sentences.csv",
        help_text="Cümle kaynağı CSV dosyası.",
        visibility="advanced",
    ),
    ParamField(
        key="content.source.generated_json",
        label="Generated Content JSON",
        group="Content",
        field_type="path",
        default="data/content/content_bank.json",
        help_text="Normalize edilmiş içerik JSON dosyası.",
        visibility="advanced",
    ),
    ParamField(
        key="content.source.label_registry_csv",
        label="Label Registry CSV",
        group="Content",
        field_type="path",
        default="data/content/label_registry.csv",
        help_text="Dinamik üretilen etiket registry CSV dosyası.",
        visibility="advanced",
    ),
    ParamField(
        key="content.generate_json_if_missing",
        label="Generate JSON If Missing",
        group="Content",
        field_type="bool",
        default=True,
        help_text="JSON yoksa otomatik üret.",
        visibility="advanced",
    ),
    ParamField(
        key="content.regenerate_json_on_start",
        label="Regenerate JSON On Start",
        group="Content",
        field_type="bool",
        default=False,
        help_text="Her başlangıçta JSON yeniden üret.",
        visibility="advanced",
    ),
    ParamField(
        key="content.mixed_probs",
        label="Mixed Mode Probabilities",
        group="Content",
        field_type="json",
        default={"chars": 0.10, "words": 0.45, "sentences": 0.45},
        help_text="Mixed text mode için olasılık dağılımı.",
        visibility="advanced",
    ),
    ParamField(
        key="content.chars",
        label="Chars Config",
        group="Content",
        field_type="json",
        default={},
        help_text="Karakter modu ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="content.words",
        label="Words Config",
        group="Content",
        field_type="json",
        default={},
        help_text="Kelime modu ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="content.sentences",
        label="Sentences Config",
        group="Content",
        field_type="json",
        default={},
        help_text="Cümle modu ayarları.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / LATEX
    # =========================================================
    ParamField(
        key="latex.enable",
        label="Enable LaTeX",
        group="LaTeX",
        field_type="bool",
        default=True,
        help_text="LaTeX/math üretimini aç/kapat.",
        visibility="advanced",
    ),
    ParamField(
        key="latex.miktex_bin",
        label="MiKTeX Bin",
        group="LaTeX",
        field_type="path",
        default=None,
        help_text="MiKTeX bin klasörü. PATH dışında ise belirt.",
        visibility="advanced",
    ),
    ParamField(
        key="latex.compiler",
        label="LaTeX Compiler",
        group="LaTeX",
        field_type="enum",
        default="pdflatex",
        choices=["pdflatex", "xelatex", "lualatex"],
        help_text="Kullanılacak LaTeX derleyicisi.",
        visibility="advanced",
    ),
    ParamField(
        key="latex.timeout_s",
        label="LaTeX Timeout (s)",
        group="LaTeX",
        field_type="int",
        default=12,
        minimum=1,
        help_text="LaTeX render timeout süresi.",
        visibility="advanced",
    ),
    ParamField(
        key="latex.raster_dpi",
        label="LaTeX Raster DPI",
        group="LaTeX",
        field_type="int",
        default=300,
        minimum=72,
        help_text="LaTeX raster çıktı DPI değeri.",
        visibility="advanced",
    ),
    ParamField(
        key="latex.level",
        label="LaTeX Difficulty",
        group="LaTeX",
        field_type="enum",
        default="medium",
        choices=["clean", "medium", "heavy"],
        help_text="Math expression üretim karmaşıklığı.",
        visibility="advanced",
    ),
    ParamField(
        key="latex.allowed_ops",
        label="Allowed Math Operations",
        group="LaTeX",
        field_type="json",
        default=[
            "add_sub",
            "multiply",
            "fraction",
            "power",
            "root",
            "trig",
            "log_exp",
            "integral",
            "sum_product",
            "matrix",
            "probability",
            "set",
            "piecewise",
        ],
        help_text="İzin verilen math işlem aileleri.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / RENDER
    # =========================================================
    ParamField(
        key="render.text",
        label="Render Text Config",
        group="Render",
        field_type="json",
        default={},
        help_text="Metin render ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="render.non_text",
        label="Render Non-Text Config",
        group="Render",
        field_type="json",
        default={},
        help_text="Non-text render ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="render.latex",
        label="Render Latex Config",
        group="Render",
        field_type="json",
        default={},
        help_text="LaTeX render ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="style",
        label="Style Config",
        group="Render",
        field_type="json",
        default={},
        help_text="Style / contrast / local mode ayarları.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / AUGMENT
    # =========================================================
    ParamField(
        key="augment.selection_policy",
        label="Augment Selection Policy",
        group="Augment",
        field_type="json",
        default={},
        help_text="Noise seviyesine göre augment seçim politikası.",
        visibility="advanced",
    ),
    ParamField(
        key="augment.photometric",
        label="Photometric Config",
        group="Augment",
        field_type="json",
        default={},
        help_text="Photometric augment ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="augment.blur_noise",
        label="Blur Noise Config",
        group="Augment",
        field_type="json",
        default={},
        help_text="Blur/noise augment ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="augment.capture_sim",
        label="Capture Simulation Config",
        group="Augment",
        field_type="json",
        default={},
        help_text="Capture simulation ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="augment.geometry",
        label="Geometry Config",
        group="Augment",
        field_type="json",
        default={},
        help_text="Geometric augment ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="augment.edge_degredation",
        label="Edge Degradation Config",
        group="Augment",
        field_type="json",
        default={},
        help_text="Edge degradation ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="augment.elastic_distortion",
        label="Elastic Distortion Config",
        group="Augment",
        field_type="json",
        default={},
        help_text="Elastic distortion ayarları.",
        visibility="advanced",
    ),
    ParamField(
        key="augment.min_area_px",
        label="Augment Min Area PX",
        group="Augment",
        field_type="int",
        default=25,
        minimum=1,
        help_text="Geometry sonrası minimum bbox alanı.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / QC
    # =========================================================
    ParamField(
        key="qc.dist_tolerance_abs",
        label="QC Dist Tolerance",
        group="QC",
        field_type="float",
        default=0.03,
        minimum=0.0,
        maximum=1.0,
        step=0.001,
        help_text="QC dağılım toleransı.",
        visibility="advanced",
    ),

    # =========================================================
    # ADVANCED / TELEMETRY
    # =========================================================
    ParamField(
        key="telemetry.mode",
        label="Telemetry Mode",
        group="Telemetry",
        field_type="enum",
        default="single_line",
        choices=["single_line", "multi_line"],
        help_text="İlerleme gösterim modu.",
        visibility="advanced",
    ),
    ParamField(
        key="telemetry.ascii_only",
        label="ASCII Only",
        group="Telemetry",
        field_type="bool",
        default=True,
        help_text="ASCII-only çıktı kullan.",
        visibility="advanced",
    ),
    ParamField(
        key="telemetry.update_interval_s",
        label="Telemetry Update Interval",
        group="Telemetry",
        field_type="float",
        default=1.2,
        minimum=0.1,
        step=0.1,
        help_text="İlerleme güncelleme aralığı.",
        visibility="advanced",
    ),
    ParamField(
        key="telemetry.show_eta",
        label="Show ETA",
        group="Telemetry",
        field_type="bool",
        default=True,
        help_text="ETA göster.",
        visibility="advanced",
    ),
    ParamField(
        key="telemetry.show_rate",
        label="Show Rate",
        group="Telemetry",
        field_type="bool",
        default=True,
        help_text="Üretim hızını göster.",
        visibility="advanced",
    ),
    ParamField(
        key="telemetry.temperature.require_temp_sensor",
        label="Require Temp Sensor",
        group="Telemetry",
        field_type="bool",
        default=True,
        help_text="Sıcaklık sensörü yoksa hata ver.",
        visibility="advanced",
    ),
    ParamField(
        key="telemetry.temperature.prefer_gpu",
        label="Prefer GPU Temperature",
        group="Telemetry",
        field_type="bool",
        default=True,
        help_text="Mümkünse GPU sıcaklığını tercih et.",
        visibility="advanced",
    ),
]


def get_param_schema() -> List[ParamField]:
    return list(_PARAM_FIELDS)


def get_param_groups(visibility: str | None = None) -> Dict[str, List[ParamField]]:
    out: Dict[str, List[ParamField]] = {}
    for field in _PARAM_FIELDS:
        if visibility is not None and field.visibility != visibility:
            continue
        out.setdefault(field.group, []).append(field)
    return out