# src/docsynthfab/orchestrator/_param_fields_basic.py
# Önerilen sürüm aralıkları:
# - Python>=3.10,<3.14

from __future__ import annotations

from typing import List

from .models import ParamField


BASIC_FIELDS: List[ParamField] = [
    ParamField(
        key="run.pages",
        label="Pages",
        group="Run",
        field_type="int",
        default=100,
        minimum=1,
        help_text="Üretilecek toplam sayfa sayısı.",
        visibility="basic",
    ),
    ParamField(
        key="run.workers",
        label="Workers",
        group="Run",
        field_type="int",
        default=4,
        minimum=1,
        help_text="Paralel worker sayısı.",
        visibility="basic",
    ),
    ParamField(
        key="run.seed",
        label="Seed",
        group="Run",
        field_type="int",
        default=1337,
        help_text="Deterministik tekrar üretim için tohum değeri.",
        visibility="basic",
    ),
    ParamField(
        key="io.out_root",
        label="Output Root",
        group="Run",
        field_type="path",
        default="",
        help_text="Çıktı klasörü.",
        visibility="basic",
    ),
    ParamField(
        key="run.export_targets",
        label="Export Targets",
        group="Output / Export",
        field_type="json",
        default=["native", "segformer", "coco"],
        help_text='Active export targets. Example: ["native", "segformer", "coco"]. Future targets: yolo, paddleocr_det, paddleocr_rec, trocr, latex_ocr, table_parser.',
        visibility="basic",
    ),
    ParamField(
        key="page.default_size",
        label="Default Page Size",
        group="Page",
        field_type="enum",
        default="a4_portrait",
        choices=[
            "a4_portrait",
            "a4_landscape",
            "letter_portrait",
            "letter_landscape",
            "legal_portrait",
            "legal_landscape",
            "a5_portrait",
            "a5_landscape",
            "b5_portrait",
            "b5_landscape",
            "executive_portrait",
            "executive_landscape",
            "tabloid_portrait",
            "tabloid_landscape",
        ],
        help_text="Varsayılan sayfa boyutu.",
        visibility="basic",
    ),
    ParamField(
        key="content.text_mode",
        label="Text Mode",
        group="Content",
        field_type="enum",
        default="mixed",
        choices=["chars", "words", "sentences", "mixed"],
        help_text="Metin üretim modu.",
        visibility="basic",
    ),
    ParamField(
        key="content.text_order",
        label="Text Order",
        group="Content",
        field_type="enum",
        default="random",
        choices=["random", "sequential"],
        help_text="Kelime/cümlelerin rastgele ya da sıralı seçimi.",
        visibility="basic",
    ),
    ParamField(
        key="content.block_mix.text",
        label="Text (%)",
        group="Content",
        field_type="float",
        default=60.0,
        minimum=0.0,
        maximum=100.0,
        step=1.0,
        help_text="Yazı bloklarının içerik karışımındaki yüzdesi. Text + Table + LaTeX toplamı 100 olmalıdır; sistem gerekirse normalize eder.",
        visibility="basic",
    ),
    ParamField(
        key="content.block_mix.table",
        label="Table (%)",
        group="Content",
        field_type="float",
        default=25.0,
        minimum=0.0,
        maximum=100.0,
        step=1.0,
        help_text="Tablo bloklarının içerik karışımındaki yüzdesi. 100 olursa backend sadece tablo blokları üretir.",
        visibility="basic",
    ),
    ParamField(
        key="content.block_mix.latex",
        label="LaTeX (%)",
        group="Content",
        field_type="float",
        default=15.0,
        minimum=0.0,
        maximum=100.0,
        step=1.0,
        help_text="LaTeX/math bloklarının içerik karışımındaki yüzdesi. 100 olursa backend sadece LaTeX/equation blokları üretir.",
        visibility="basic",
    ),
    ParamField(
        key="augment.enable",
        label="Enable Augment",
        group="Augment",
        field_type="bool",
        default=True,
        help_text="Render sonrası augment işlemlerini aç/kapat.",
        visibility="basic",
    ),
]



